config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  resources :results
  resources :groups
  resources :competitions
  resources :runners
  resources :clubs
  resources :categories
  get 'home/wredata'
  get 'home/wre_id'
  get 'home/wre_results_men'
  get 'home/wre_results_women'
  get 'home/wredata'



  root to: 'home#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/competition.rb
class Competition < ApplicationRecord
end

app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController
  before_action :set_competition, only: %i[ show edit update destroy ]

  # GET /competitions or /competitions.json
  def index
    @competitions = Competition.all
  end

  # GET /competitions/1 or /competitions/1.json
  def show
  end

  # GET /competitions/new
  def new
    @competition = Competition.new
  end

  # GET /competitions/1/edit
  def edit
  end

  # POST /competitions or /competitions.json
  def create
    @competition = Competition.new(competition_params)

    respond_to do |format|
      if @competition.save
        format.html { redirect_to competition_url(@competition), notice: "Competition was successfully created." }
        format.json { render :show, status: :created, location: @competition }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @competition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /competitions/1 or /competitions/1.json
  def update
    respond_to do |format|
      if @competition.update(competition_params)
        format.html { redirect_to competition_url(@competition), notice: "Competition was successfully updated." }
        format.json { render :show, status: :ok, location: @competition }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @competition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /competitions/1 or /competitions/1.json
  def destroy
    @competition.destroy

    respond_to do |format|
      format.html { redirect_to competitions_url, notice: "Competition was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_competition
      @competition = Competition.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def competition_params
      params.require(:competition).permit(:competition_name, :date, :location, :country, :distance_type)
    end
end

app/helpers/competitions_helper.rb
module CompetitionsHelper
end

app/views/competitions/_competition.html.erb
<div id="<%= dom_id competition %>">
  <p>
    <strong>Competition name:</strong>
    <%= competition.competition_name %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= competition.date %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= competition.location %>
  </p>

  <p>
    <strong>Country:</strong>
    <%= competition.country %>
  </p>

  <p>
    <strong>Distance type:</strong>
    <%= competition.distance_type %>
  </p>

</div>

app/views/competitions/_form.html.erb
<%= form_with(model: competition) do |form| %>
  <% if competition.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(competition.errors.count, "error") %> prohibited this competition from being saved:</h2>

      <ul>
        <% competition.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :competition_name, style: "display: block" %>
    <%= form.text_field :competition_name %>
  </div>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.date_field :date %>
  </div>

  <div>
    <%= form.label :location, style: "display: block" %>
    <%= form.text_field :location %>
  </div>

  <div>
    <%= form.label :country, style: "display: block" %>
    <%= form.text_field :country %>
  </div>

  <div>
    <%= form.label :distance_type, style: "display: block" %>
    <%= form.text_field :distance_type %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/competitions/edit.html.erb
<h1>Editing competition</h1>

<%= render "form", competition: @competition %>

<br>

<div>
  <%= link_to "Show this competition", @competition %> |
  <%= link_to "Back to competitions", competitions_path %>
</div>

app/views/competitions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Competitions</h1>

<div id="competitions">
  <% @competitions.each do |competition| %>
    <%= render competition %>
    <p>
      <%= link_to "Show this competition", competition %>
    </p>
  <% end %>
</div>

<%= link_to "New competition", new_competition_path %>

app/views/competitions/new.html.erb
<h1>New competition</h1>

<%= render "form", competition: @competition %>

<br>

<div>
  <%= link_to "Back to competitions", competitions_path %>
</div>

app/views/competitions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @competition %>

<div>
  <%= link_to "Edit this competition", edit_competition_path(@competition) %> |
  <%= link_to "Back to competitions", competitions_path %>

  <%= button_to "Destroy this competition", @competition, method: :delete %>
</div>