config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  resources :results
  resources :groups
  resources :competitions
  resources :runners
  resources :clubs
  resources :categories
  get 'home/wredata'
  get 'home/wre_id'
  get 'home/wre_results_men'
  get 'home/wre_results_women'
  get 'home/wredata'



  root to: 'home#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def wre_id
    browser = Watir::Browser.new :chrome, headless: true
    browser.goto 'http://ranking.orienteering.org/ranking'
    browser.select(id: "FederationRegion").wait_until(&:present?)
    browser.select(id: "FederationRegion").select("MDA")
    sleep 0.5
    browser.button(id: "MainContent_btnShowRanking").click
    browser.span(class: "flag-MDA").wait_until(&:present?)
    ids = [{ surname: "Roman" ,name: "Ciobanu", id: "8458", gender: "M" }]
    ids += persons(browser, "M")

    browser.select(id: "MainContent_ddlGroup").select("Women")
    sleep 0.5
    browser.button(id: "MainContent_btnShowRanking").click
    browser.select(id: "MainContent_ddlGroup").wait_until { |val| val.value == "WOMEN"}
    ids += persons(browser, "F")

    new_ids = []
    exist_ids = []
    new_runner_ids = []

    ids.each do |id|
       if Runner.find_by(wre_id: id[:id])
        exist_ids << id[:id]
        next
      end
      runner =  Runner.find_by(runner_name: id[:name], surname: id[:surname])

      if runner
        runner.update(wre_id: id[:id])
        new_ids << id[:id]
      else
        new_runner_ids << id[:id]
        Runner.create(runner_name: id[:name], surname: id[:surname], gender: id[:gender], wre_id: id[:id], club_id: 0, category_id: 10 )
      end
    end
    browser.close

    render json: { new_ids: new_ids, exist_ids: exist_ids, new_runner_ids: new_runner_ids}
  end

  def wre_results_men
    @results_count = 0
    runners = Runner.where(gender: "M").where.not(wre_id: nil)
    get_results(runners)
    render json: { competitions: @results_count}
  end

  def wre_results_women
    @results_count = 0
    runners = Runner.where(gender: "F").where.not(wre_id: nil)
    get_results(runners)
    render json: { competitions: @results_count}
  end

  def wredata
    runners = Runner.where.not(wre_id: nil)

    data = runners.map do |runner|
      results = runner.results.where.not(wre_points: nil).map do |res|
        {
          date: res.group.competition.date.as_json,
          name: res.group.competition.competition_name,
          place: res.place,
          points: res.wre_points,
          category: res.category.category_name
        }
      end
      {
        name: "#{runner.runner_name} #{runner.surname}",
        wre_id: runner.wre_id,
        forest_wre_ranking: runner.forest_wre_ranking,
        sprint_wre_ranking: runner.sprint_wre_ranking,
        results: results
      }
    end
    render json: { data: data}
  end


  def persons(browser, gender)
    browser.links(href: /PersonView/).map do |link|
      {
        surname: link.text.split.first,
        name:    link.text.split.last,
        id:      link.href[/\d+/],
        gender:  gender
      }
    end
  end

  def parse_results(html, runner, distance_type = nil)
    html.at_css("table.ranktable").css("tr").drop(1).each do |tr|
      time  =tr.css("td")[4].text.split(":")
      data = {
        date: Date.strptime(tr.at_css("td").text, '%m/%d/%Y'),
        competition_name: tr.css("td")[1].text,
        cometition_id: tr.css("td")[1].at_css("a")["href"][/event=\d+/][/\d+/],
        points: tr.css("td")[-2].text.to_i,
        place: tr.css("td")[3].text.to_i,
        time: time.first.to_i * 60 + time.last.to_i
      }
      distance_type ||= case data[:competition_name]
      when /Long/i then "Long"
      when /Middle/i then "Middle"
      end

      competition = Competition.find_or_create_by(
        competition_name: data[:competition_name],
        date: data[:date],
        wre_id: data[:cometition_id],
        distance_type: distance_type
      )
      group = Group.find_or_create_by(competition: competition, group_name: "#{runner.gender.upcase.sub("F", "W")}21E")
      next if Result.find_by(runner: runner, group: group)

      category_id = case data[:points]
      when 700..999 then 3
      when 1000..1299 then 2
      when 1300..1500 then 1
      else 10
      end
      @results_count += 1
      Result.create(group: group, runner: runner, place: data[:place], time: data[:time], category_id: category_id, wre_points: data[:points] )
    end
  end

  def get_results(runners)
    browser = Watir::Browser.new :chrome, headless: true
    runners.each do |runner|
      browser.goto "https://ranking.orienteering.org/PersonView?person=#{runner[:wre_id]}"
      browser.table(class: "ranktable").wait_until(&:present?)
      html = Nokogiri::HTML(browser.html)
      # name ="#{html.at_css("span#MainContent_RunnerDetails_Label1").text} #{html.at_css("span#MainContent_RunnerDetails_Label3").text}"
      runner.update(
        forest_wre_ranking: html.at_css("a.list-group-item:not(:contains('Sprint')) span")&.text.to_i,
        sprint_wre_ranking: html.at_css("a.list-group-item:contains('Sprint') span")&.text.to_i
      )
      parse_results(html, runner)

      next unless browser.link(href: "#list", text: /Sprint/).present?

      browser.link(href: "#list", text: /Sprint/).click
      browser.table(class: "ranktable", text:/Sprint/).wait_until(&:present?)
      html = Nokogiri::HTML(browser.html)
      parse_results(html, runner, "Sprint")
    end

    browser.close
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom navbar navbar-light" style="background-color: #e3f2fd;">
    <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
        <li>
            <%=link_to  image_tag("http://orienteering.md/wp-content/uploads/2021/05/logo_fos.png", class: "header-logo"), root_path, class: "logo nav-link" %>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Database
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%=link_to 'Clubs',        clubs_path,        class: "dropdown-item" %>
                <%=link_to 'Runners',      runners_path,      class: "dropdown-item" %>
                <%=link_to 'Competitions', competitions_path, class: "dropdown-item" %>
                <%=link_to 'Groups',       groups_path,       class: "dropdown-item" %>
                <%=link_to 'Results',      results_path,      class: "dropdown-item" %>
                <%=link_to 'Categories',   categories_path,   class: "dropdown-item" %>
            </div>
        </li>
        <% if user_signed_in? %>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Add to Database
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%=link_to 'Add Clubs',        new_club_path,         class: "dropdown-item" %>
                <%=link_to 'Add Runners',      new_runner_path,       class: "dropdown-item" %>
                <%=link_to 'Add Competitions', new_competition_path,  class: "dropdown-item" %>
                <%=link_to 'Add Groups',       new_group_path,        class: "dropdown-item" %>
                <%=link_to 'Add Results',      new_result_path,       class: "dropdown-item" %>
            </div>
        </li>
        <% end %>
    </ul>

        <div class="col-md-3 text-end">
            <% if user_signed_in? %>
            <%=link_to 'Edit Profile', edit_user_registration_path, class: "btn btn-primary" %>
            <%=link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
            <% else %>
            <%=link_to 'Sign Up', new_user_registration_path, class: "btn btn-success me-2" %>
            <%=link_to 'Sign In', new_user_session_path, class: "btn btn-info" %>
            <% end %>
        </div>
</header>

app/views/home/index.html.erb
hello